name: citus-chart

global:
  imageRegistry: defaultValue

repl:
  name: citus-chart-rep

namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: apps.cicd.mdtu-ddm.projects.epam.com

database:
  required: false
  timezone: UTC

image:
  name: citus-chart
  version: latest

master:
  name: citus-master
  replicas: 1
  containers:
    name: citus
    image: citusdata/citus:10.0.2
    port: 5432
    env:
      pgdata_value: /var/lib/postgresql/data/pgdata
      user_name: username
      pgsecret_name: citus-secrets
      pgsecret_key: password
    volumeMounts:
      name: storage
      mountPath: /var/lib/postgresql/data
  volumes:
    name: storage
    claimName: citus-master-pvc
    size: 5Gi

workers:
  name: citus-workers
  replicas: 0
  containers:
    node_name: citus-worker
    image: citusdata/citus:10.0.2
    port: 5432
    env:
      pgdata_value: /var/lib/postgresql/data/pgdata
      pgsecret_name: citus-secrets
      pgsecret_key: password
    volumeMounts:
      name: storage
      mountPath: /var/lib/postgresql/data
  volumes:
    name: storage
    size: 5Gi
secret:
  name: citus-secrets

masterReplica:
  name: citus-master-rep
  replicas: 1
  containers:
    name: citus
    image: citusdata/citus:10.0.2
    port: 5432
    env:
      pgdata_value: /var/lib/postgresql/data/pgdata
      user_name: username
      pgsecret_name: citus-secrets
      pgsecret_key: password
    volumeMounts:
      name: storage
      mountPath: /var/lib/postgresql/data
  volumes:
    name: storage
    claimName: citus-master-rep-pvc
    size: 5Gi

workersReplica:
  name: citus-workers-rep
  replicas: 0
  containers:
    node_name: citus-worker-rep
    image: citusdata/citus:10.0.2
    port: 5432
    env:
      pgdata_value: /var/lib/postgresql/data/pgdata
      pgsecret_name: citus-secrets
      pgsecret_key: password
    volumeMounts:
      name: storage
      mountPath: /var/lib/postgresql/data
  volumes:
    name: storage
    size: 5Gi

storageClass: gp2

resources:
  requests:
    cpu: 100m
    memory: 1Gi

citus:
  pgpassEnvVariable: /var/lib/postgresql/data/.pgpass
  serviceAccountName: citus
  securityContext:
    runAsUser: 999
    fsGroup: 999
  dbName: registry
  archiveSchema: archive
  pubHost: citus-master
  pubUser: postgres
  pubPort: 5432
  secrets:
    citusSecrets:
      pgsecretName: citus-secrets
      userName: username
      pgsecretKey: password
      rolesSecret: citus-roles-secrets
    citusRolesSecrets:
      anAdm: analytics_admin
      anRole: analytics_auditor
      anSvc: audit_service_user
      settRole: settings_role
      excerptExporter: excerpt_exporter
      excerptSvc: excerpt_service_user
      excerptWork: excerpt_worker_user
      regOwner: registry_owner_role
      appRole: application_role
      admRole: admin_role
      histRole: historical_data_role

  url:
    masterDBurl: jdbc:postgresql://citus-master:5432
    replicaDBurl: jdbc:postgresql://citus-master-rep:5432
