name: citus-chart

repl:
  name: citus-chart-rep

namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: apps.cicd.mdtu-ddm.projects.epam.com

database:
  required: false
  timezone: UTC

image:
  name: citus-chart
  version: latest

master:
  name: citus-master
  replicas: 1
  containers:
    name: citus
    image: citusdata/citus:10.0.2
    port: 5432
    env:
      pgdata_value: /var/lib/postgresql/data/pgdata
      user_name: username
      pgsecret_name: citus-secrets
      pgsecret_key: password
    volumeMounts:
      name: storage
      mountPath: /var/lib/postgresql/data
  volumes:
    name: storage
    claimName: citus-master-pvc
    size: 5Gi

workers:
  name: citus-workers
  replicas: 0
  containers:
    node_name: citus-worker
    image: citusdata/citus:10.0.2
    port: 5432
    env:
      pgdata_value: /var/lib/postgresql/data/pgdata
      pgsecret_name: citus-secrets
      pgsecret_key: password
    volumeMounts:
      name: storage
      mountPath: /var/lib/postgresql/data
  volumes:
    name: storage
    size: 5Gi
secret:
  name: citus-secrets


masterReplica:
  name: citus-master-rep
  replicas: 1
  containers:
    name: citus
    image: citusdata/citus:10.0.2
    port: 5432
    env:
      pgdata_value: /var/lib/postgresql/data/pgdata
      user_name: username
      pgsecret_name: citus-secrets
      pgsecret_key: password
    volumeMounts:
      name: storage
      mountPath: /var/lib/postgresql/data
  volumes:
    name: storage
    claimName: citus-master-rep-pvc
    size: 5Gi

workersReplica:
  name: citus-workers-rep
  replicas: 0
  containers:
    node_name: citus-worker-rep
    image: citusdata/citus:10.0.2
    port: 5432
    env:
      pgdata_value: /var/lib/postgresql/data/pgdata
      pgsecret_name: citus-secrets
      pgsecret_key: password
    volumeMounts:
      name: storage
      mountPath: /var/lib/postgresql/data
  volumes:
    name: storage
    size: 5Gi

storageClass: gp2

resources:
  requests:
    cpu: 100m
    memory: 1Gi

citus:
  dbName: registry
  archiveSchema: archive
  pubHost: citus-master
  pubUser: postgres
  pubPort: 5432
  secrets:
    citusSecrets:
      pgsecretName: citus-secrets
      userName: username
      pgsecretKey: password
      rolesSecret: citus-roles-secrets
    citusRolesSecretsName:
      - anAdmName
      - anRoleName 
      - anSvcName
      - settRoleName
      - excerptExporterName
      - excerptSvcName
      - excerptWorkName
      - regOwnerName
      - appRoleName
      - admRoleName
      - histRoleName
    citusRolesSecretsPass:
      - regOwnerPass
      - appRolePass
      - admRolePass
      - settRolePass
      - anRolePass
      - excerptSvcPass
      - excerptWorkPass
      - excerptExporterPass
      - anAdmPass
      - anSvcPass
      - histRolePass
  url:
    masterDBurl: jdbc:postgresql://citus-master:5432
    replicaDBurl: jdbc:postgresql://citus-master-rep:5432