apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.masterReplica.name }}
  labels:
    app: {{ .Values.masterReplica.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.masterReplica.name }}
  replicas: {{ .Values.masterReplica.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: {{ .Values.masterReplica.volumes.name }}
        sidecar.istio.io/inject: "false"
      labels:
        app: {{ .Values.masterReplica.name }}
    spec:
      initContainers:
        - name: init-chown-data
          image: {{ template "imageRegistry" . -}} busybox
          command: [ 'sh', '-c', 'chmod 0700 -R /data/pgdata || true' ]
          volumeMounts:
            - name: {{ .Values.masterReplica.volumes.name }}
              mountPath: /data
      containers:
      - name: {{ .Values.masterReplica.containers.name }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        image: {{ template "imageRegistry" . -}} {{ .Values.masterReplica.containers.image }}
        imagePullPolicy: IfNotPresent
        command: [ "docker-entrypoint.sh", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
        ports:
        - containerPort: {{ .Values.masterReplica.containers.port }}
        env:
        {{- $rolesSecret := .Values.citus.secrets.citusSecrets.rolesSecret }}
        {{- range $k, $v := .Values.citus.secrets.citusRolesSecrets }}
          {{- $valPass := (print $v "_pass") }}
          {{- $keyPass := (print $k "Pass") }}
        - name: {{ $valPass }}
          valueFrom:
            secretKeyRef:
              name: {{ $rolesSecret }}
              key: {{ $keyPass }}
        {{- end }}
        - name: PGDATA
          value: {{ .Values.masterReplica.containers.env.pgdata_value }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.masterReplica.containers.env.pgsecret_name }}
              key: {{ .Values.masterReplica.containers.env.pgsecret_key }}
        - name: PGTZ
          value: {{ .Values.database.timezone }}
        - name: PGPASSFILE
          value: {{ .Values.citus.pgpassEnvVariable }}
        volumeMounts:
        - name: {{ .Values.masterReplica.containers.volumeMounts.name }}
          mountPath: {{ .Values.masterReplica.containers.volumeMounts.mountPath }}
        - name: pg-conf
          mountPath: /etc/postgresql
        - name: pgpass
          mountPath: /docker-entrypoint-initdb.d/002-create-pgpass.sh
          subPath: 002-create-pgpass.sh
        livenessProbe:
          exec:
            command:
            - ./pg_healthcheck
          initialDelaySeconds: 60
      securityContext:
        runAsUser: {{ .Values.citus.securityContext.runAsUser }}
        fsGroup: {{ .Values.citus.securityContext.fsGroup }}
      serviceAccountName: {{ .Values.citus.serviceAccountName }}
      volumes:
        - name: {{ .Values.masterReplica.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.masterReplica.volumes.claimName }}
        - name: pg-conf
          configMap:
            name: pgconfig
        - name: pgpass
          configMap:
            name: pgpass
        - name: citus-create-roles
          configMap:
            name: citus-create-roles
