apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.master.name }}
  labels:
    app: {{ .Values.master.name }}
spec:
  selector:
    app: {{ .Values.master.name }}
  clusterIP: None
  ports:
  - port: {{ .Values.master.containers.port }}