apiVersion: v1
kind: ConfigMap
metadata:
  name: create-roles-on-replica
data:
  registry_db__create_roles_on_replica.sql:
{{ (.Files.Glob "sql-scripts-on-stage/registry_db__create_roles_on_replica.sql").AsConfig | indent 2 }}