apiVersion: batch/v1
kind: Job
metadata:
  name: "db-objects-setup-on-citus-master"
  annotations:
    # This is what defines this resource as a hook.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "citus-master-setup-job"
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/name: "citus-master-setup-job"
        app.kubernetes.io/instance: "master"
    spec:
      serviceAccountName: {{ .Values.name }}
      restartPolicy: Never
      containers:
        - name: "db-objects-setup-master"
          image: {{ .Values.dockerProxyRegistry }}/bitnami/postgresql:latest
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - '-c'
            - >-
              bash /etc/script_with_psql_commands_for_master.sh
          volumeMounts:
            - name: excerpt-db
              mountPath: /etc/create_excerpt_db_on_master.sql
              readOnly: true
              subPath: create_excerpt_db_on_master.sql
            - name: settings-db
              mountPath: /etc/create_settings_db_on_master.sql
              readOnly: true
              subPath: create_settings_db_on_master.sql
            - name: audit-db
              mountPath: /etc/create_audit_db_on_master.sql
              readOnly: true
              subPath: create_audit_db_on_master.sql
            - name: all-other-on-master-db
              mountPath: /etc/create_all_others_on_master.sql
              readOnly: true
              subPath: create_all_others_on_master.sql
            - name: script-with-psql-commands
              mountPath: /etc/script_with_psql_commands_for_master.sh
              readOnly: true
              subPath: script_with_psql_commands_for_master.sh
          env:
            - name: REG_OWNER
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: regOwnerName
            - name: REG_OWNER_PASS
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: regOwnerPass
            - name: APP_ROLE
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: appRoleName
            - name: APP_PASS
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: appRolePass
            - name: EXCERPT_SVC_USER
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: excerptSvcUser
            - name: EXCERPT_SVC_PASS
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: excerptSvcPass
            - name: EXCERPT_WORK_USER
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: excerptWorkUser
            - name: EXCERPT_WORK_PASS
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: excerptWorkPass
            - name: ADM_ROLE
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: admRoleName
            - name: ADM_PASS
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: admRolePass
            - name: SETT_ROLE
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: settRoleName
            - name: SETT_PASS
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: settRolePass
            - name: AN_ROLE
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: anRoleName
            - name: AN_PASS
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: anRolePass
            - name: AN_ADM_ROLE
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: anAdmUser
            - name: AN_ADM_PASS
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: anAdmPass
            - name: EXPORTER_USER
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: excerptExporterUser
            - name: EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: excerptExporterPass
            - name: AN_SVC_USER
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: anSvcUser
            - name: AN_SVC_PASS
              valueFrom:
                secretKeyRef:
                  name: citus-roles-secrets
                  key: anSvcPass
            - name: PSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.master.containers.env.pgsecret_name }}
                  key: {{ .Values.master.containers.env.user_name }}
            - name: PGDATA
              value: {{ .Values.master.containers.env.pgdata_value }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.master.containers.env.pgsecret_name }}
                  key: {{ .Values.master.containers.env.pgsecret_key }}
            - name: PGTZ
              value: {{ .Values.database.timezone }}
      volumes:
        - name: excerpt-db
          configMap:
            name: excerpt-db
        - name: settings-db
          configMap:
            name: settings-db
        - name: audit-db
          configMap:
            name: audit-db
        - name: all-other-on-master-db
          configMap:
            name: all-other-on-master-db
        - name: script-with-psql-commands
          configMap:
            name: script-with-psql-commands
            defaultMode: 0775