apiVersion: v1
kind: ConfigMap
metadata:
  name: grants-after-deploy-on-replica
data:
  registry_db__grants_after_deploy_on_replica.sql:
{{ (.Files.Glob "sql-scripts-on-stage/registry_db__grants_after_deploy_on_replica.sql").AsConfig | indent 2 }}