apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgpool
      postgres-operator.crunchydata.com/cluster: operational
  template:
    metadata:
      labels:
        app: pgpool
        postgres-operator.crunchydata.com/cluster: operational
    spec:
      containers:
      - name: pgpool
        image: pgpool/pgpool
        env:
        {{- $rolesSecret := .Values.postgresCluster.secrets.citusSecrets.rolesSecret }}
        {{- range $k,$v := .Values.postgresCluster.secrets.citusRolesSecrets }}
        {{- $varName := (print $k "_USERNAME") | upper }}
        {{- $keyName := (print $k "Name") }}
        - name: {{ $varName }}
          valueFrom:
            secretKeyRef:
              name: {{ $rolesSecret }}
              key: {{ $keyName }}
        {{- end }}
        {{- range $k,$v := .Values.postgresCluster.secrets.citusRolesSecrets }}
        {{- $varPassName := (print $k "_PASSWORD") | upper }}
        {{- $keyPass := (print $k "Pass") }}
        - name: {{ $varPassName }}
          valueFrom:
            secretKeyRef:
              name: {{ $rolesSecret }}
              key: {{ $keyPass }}
        {{- end }}
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: operational-pguser-postgres
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: operational-pguser-postgres
              key: password
        #- name: PASSWORD_AUTHENTICATION
        #  value: "md5"
        volumeMounts:
        - name: pgpool-config
          mountPath: /config
      volumes:
      - name: pgpool-config
        configMap:
          name: pgpool-config
      serviceAccount: {{ .Values.postgresCluster.serviceAccountName }}
      securityContext:
        runAsUser: 70
        fsGroup: 70
---
apiVersion: v1
kind: Service
metadata:
  name: pgpool
spec:
  selector:
    app: pgpool
  ports:
  - name: pgpool-port
    protocol: TCP
    port: 5432
    targetPort: 5432
