{{- $secret := (lookup "v1" "Secret" .Values.namespace .Values.citus.secrets.citusSecrets.rolesSecret ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: citus-roles-secrets
type: Opaque
data:
  {{- if not $secret }}
  {{- range $key := .Values.citus.secrets.citusRolesSecretsPass }}
  {{ $key }}: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
  {{- else }}
  {{- range $key := .Values.citus.secrets.citusRolesSecretsPass }}
  {{- if hasKey $secret.data $key }}
  {{ $key }}: {{ index $secret.data $key }}
  {{- else }}
  {{ $key }}: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  regOwnerName: cmVnaXN0cnlfb3duZXJfcm9sZQ==
  appRoleName: YXBwbGljYXRpb25fcm9sZQ==
  admRoleName: YWRtaW5fcm9sZQ==
  settRoleName: c2V0dGluZ3Nfcm9sZQ==
  anRoleName: YW5hbHl0aWNzX2F1ZGl0b3I=
  excerptSvcName: ZXhjZXJwdF9zZXJ2aWNlX3VzZXI=
  excerptWorkName: ZXhjZXJwdF93b3JrZXJfdXNlcg==
  excerptExporterName: ZXhjZXJwdF9leHBvcnRlcg==
  anAdmName: YW5hbHl0aWNzX2FkbWlu
  anSvcName: YXVkaXRfc2VydmljZV91c2Vy
  histRoleName: aGlzdG9yaWNhbF9kYXRhX3JvbGU=