apiVersion: v1
kind: Secret
metadata:
  name: citus-roles-secrets
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque
data:
  regOwnerName: cmVnaXN0cnlfb3duZXJfcm9sZQ==
  regOwnerPass: {{ randAlphaNum 12 | b64enc | quote }}
  appRoleName: YXBwbGljYXRpb25fcm9sZQ==
  appRolePass: {{ randAlphaNum 12 | b64enc | quote }}
  admRoleName: YWRtaW5fcm9sZQ==
  admRolePass: {{ randAlphaNum 12 | b64enc | quote }}
  settRoleName: c2V0dGluZ3Nfcm9sZQ==
  settRolePass: {{ randAlphaNum 12 | b64enc | quote }}
  anRoleName: YW5hbHl0aWNzX2F1ZGl0b3I=
  anRolePass: {{ randAlphaNum 12 | b64enc | quote }}
  excerptSvcUser: ZXhjZXJwdF9zZXJ2aWNlX3VzZXI=
  excerptSvcPass: {{ randAlphaNum 12 | b64enc | quote }}
  excerptWorkUser: ZXhjZXJwdF93b3JrZXJfdXNlcg==
  excerptWorkPass: {{ randAlphaNum 12 | b64enc | quote }}
  excerptExporterUser: ZXhjZXJwdF9leHBvcnRlcg==
  excerptExporterPass: {{ randAlphaNum 12 | b64enc | quote }}
  anAdmUser: YW5hbHl0aWNzX2FkbWlu
  anAdmPass: {{ randAlphaNum 12 | b64enc | quote }}
  anSvcUser: YXVkaXRfc2VydmljZV91c2Vy
  anSvcPass: {{ randAlphaNum 12 | b64enc | quote }}